// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRD_SuperToolsEngine","status":true,"description":"The heart of all maker-style plugins; it adds a playtesting editor that can be opened with F12.","parameters":{"Connect Editor":"true","Auto Open Window":"false","Auto Move Window":"true","Menu Editor Exempt List":"[\"Window_BattleLog\",\"Window_MapName\"]"}},
{"name":"SRD_HUDMaker","status":true,"description":"Allows developers to create their own map-based HUD through an in-game GUI window!","parameters":{"Active Updating":"false","Show During Events":"off","Map Global Condition":"","Battle Global Condition":"","Disable Delete Key":"true"}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"GALV_ActionIndicators","status":true,"description":"Display an icon when the player is able to interact with an event. View help for comment tag.","parameters":{"Y Offset":"0","Z Position":"5","Auto Hide":"true","Icon Opacity":"200"}},
{"name":"GALV_EventDetectors","status":true,"description":"Have events activate when player gets in range and line of sight.","parameters":{"LOS Blocking Terrain":"5,6","LOS Blocking Regions":"1,2","Tile Size":"48","Search Limit":"24","--- Behaviors ---":"","Behavior 0":"","Behavior 1":"","Behavior 2":"","Behavior 3":"","Behavior 4":"","Behavior 5":"","Behavior 6":"","Behavior 7":"","Behavior 8":"","Behavior 9":"","Behavior 10":"","Behavior 11":"","Behavior 12":"","Behavior 13":"","Behavior 14":"","Behavior 15":"","Behavior 16":"","Behavior 17":"","Behavior 18":"","Behavior 19":"","Behavior 20":""}},
{"name":"Izy_FastFace (3)","status":true,"description":"v1.01 This plugin make your text show face faster and easier.","parameters":{"Default Face Name":"Actor1","Default Face Index":"0"}}
];
